### ISSUE TITLE
输入mac后连接失败

### ISSUE THREAD

**Issue by xizeyoupan** [quantum818/HC05-base-Android-#1]
![Screenshot_2021-12-16-23-58-39-622_com.example.test1.jpg](https://user-images.githubusercontent.com/44920131/146405678-42286298-169b-4c24-b04b-6d1aa335bf9b.jpg)

**Comment by quantum818** [comment]
可以试试多按几次蓝牙连接的按键，目前我还没有试验连接HC-05以外的蓝牙设备。最好还是使用xizeyoupan的今典蓝牙串口助手。

**Comment by xizeyoupan** [comment]
请问作者您自个能用手机连到您的电脑吗

**Comment by quantum818** [comment]
哈哈还没有试捏
